CREATE DATABASE IF NOT EXISTS dbbwt;

USE dbbwt;

CREATE TABLE IF NOT EXISTS `USER` (
	`USER_UID`	CHAR(6)	NOT NULL PRIMARY KEY COMMENT '000000',
	`USER_ID`	VARCHAR(64)	NOT NULL	COMMENT '4~64자 문자열',
	`USER_TYPE_CD`	TINYINT	NOT NULL	DEFAULT 9	COMMENT '1:개인, 2:기업, 9:관리자',
	`USER_NAME`	VARCHAR(30)	NOT NULL,
	`USER_NICK_NAME`	VARCHAR(30)	NULL,
	`USER_PW`	VARCHAR(600)	NOT NULL	COMMENT '8-124자 문자열, 암호화',
	`USER_PHONE`	VARCHAR(20)	NULL,
	`USER_MAIL`	VARCHAR(100)	NULL,
	`USER_COMPANY`	VARCHAR(200)	NULL,
	`USER_IMG`	VARCHAR(300)	NULL,
	`USER_JOIN_DATE`	DATETIME	NOT NULL,
	`USER_MODI_DATE`	DATETIME	NOT NULL,
	`DEL_YN`	VARCHAR(1)	NOT NULL	DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS `BOARD` (
	`BOARD_ID`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`USER_UID`	CHAR(6)	NOT NULL	COMMENT '000000',
	`BOARD_TYPE_CD`	CHAR(1)	NOT NULL	DEFAULT 'A'	COMMENT 'BOARD_TYPE(A:제품소개, B:적용사례, C:공지사항, D:자료실, E:제품문의)',
	`CATEGORY_TYPE_CD`	CHAR(1)	NOT NULL	DEFAULT 1,
	`TITLE`	VARCHAR(255)	NOT NULL,
	`TITLE_ENG`	VARCHAR(255)	NULL,
	`SUB_TITLE`	VARCHAR(1000)	NULL,
	`CONTENT`	LONGTEXT	NULL,
	`CONTENT_TXT`	LONGTEXT	NULL,
	`CONTENT_ENG`	LONGTEXT	NULL,
  `CONTENT_ENG_TXT`	LONGTEXT	NULL,
	`THUMNAIL_IMG`	VARCHAR(300)	NULL,
	`URL1`	VARCHAR(100)	NULL,
	`URL2`	VARCHAR(100)	NULL,
	`KEYWORD`	VARCHAR(300)	NULL,
	`VIEW_CNT`	INT	NOT NULL	DEFAULT 0,
	`SCRAP_CNT`	INT	NOT NULL	DEFAULT 0,
	`MAIN_YN`	CHAR(1)	NOT NULL	DEFAULT 'Y',
	`PRODUCT_DESC`	VARCHAR(1000)	NULL,
	`PRODUCT_DESC_ENG`	VARCHAR(1000)	NULL,
	`WRITER`	VARCHAR(100)	NULL,
	`WRITER_PHONE`	VARCHAR(20)	NULL,
	`WRITER_MAIL`	VARCHAR(100)	NULL,
	`WRITER_COMPANY`	VARCHAR(200)	NULL,
	`DEL_YN`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`REG_USER_UID`	VARCHAR(64)	NOT NULL,
	`REG_TIME`	DATETIME	NOT NULL,
	`MODI_USER_UID`	VARCHAR(64)	NOT NULL,
	`MODI_TIME`	DATETIME	NOT NULL
);

CREATE TABLE IF NOT EXISTS `BOARD_TYPE` (
	`TYPE_CD`	CHAR(1)	NOT NULL PRIMARY KEY,
	`TYPE_NAME`	VARCHAR(100)	NOT NULL,
	`TYPE_ENG_NAME`	VARCHAR(255)	NULL,
	`USE_YN`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS `CATEGORY_TYPE` (
	`TYPE_CD`	CHAR(1)	NOT NULL PRIMARY KEY,
	`TYPE_NAME`	VARCHAR(100)	NOT NULL,
	`TYPE_ENG_NAME`	VARCHAR(255)	NULL,
	`USE_YN`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS `FILE` (
	`FILE_ID`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`BOARD_ID`	INT	NOT NULL,
	`FILE_PATH`	VARCHAR(600)	NOT NULL	COMMENT '파일 상위까지의 경로',
	`FILE_NAME`	VARCHAR(255)	NOT NULL	COMMENT '파일명+확장자',
	`FILE_NAME_ORG`	VARCHAR(255)	NOT NULL	COMMENT '파일명+확장자',
	`FILE_SIZE`	int(11)	NULL	COMMENT '파일확장자',
	`FILE_EXT`	VARCHAR(4)	NULL	COMMENT '파일확장자',
	`FILE_NOTE`	VARCHAR(600)	NULL,
	`DEL_YN`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`REG_USER_UID`	VARCHAR(64)	NOT NULL,
	`REG_TIME`	DATETIME	NOT NULL,
	`MODI_USER_UID`	VARCHAR(64)	NOT NULL,
	`MODI_TIME`	DATETIME	NOT NULL
);

INSERT INTO USER
	(USER_UID, USER_ID, USER_TYPE_CD, USER_NAME, USER_NICK_NAME, USER_COMPANY,
	USER_PW, USER_PHONE, USER_MAIL,
	USER_JOIN_DATE, USER_MODI_DATE, DEL_YN)
SELECT
	'000001', 'bwtadmin', '9', '블루웨이브텔', '블루웨이브텔', '블루웨이브텔',
	'a5ceb7d5592fe3c2dd04754faab8d69912ea828d97d3339ed6e5acfdad6dafb5', '01000000000', 'kimsj@hs-com.co.kr',
	CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'N'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM USER WHERE USER_UID = '000001'
);

INSERT INTO BOARD_TYPE
	(TYPE_CD, TYPE_NAME, TYPE_ENG_NAME, USE_YN)
SELECT
	'A', '제품소개', 'product', 'Y'
FROM DUAL
WHERE NOT EXISTS (
	SELECT 1 FROM BOARD_TYPE WHERE TYPE_CD = 'A'
);


INSERT INTO BOARD_TYPE
	(TYPE_CD, TYPE_NAME, TYPE_ENG_NAME, USE_YN)
SELECT
	'B', '적용사례', 'case', 'Y'
FROM DUAL
WHERE NOT EXISTS (
	SELECT 1 FROM BOARD_TYPE WHERE TYPE_CD = 'B'
);

INSERT INTO BOARD_TYPE
	(TYPE_CD, TYPE_NAME, TYPE_ENG_NAME, USE_YN)
SELECT
	'C', '공지사항', 'notice', 'Y'
FROM DUAL
WHERE NOT EXISTS (
	SELECT 1 FROM BOARD_TYPE WHERE TYPE_CD = 'C'
);

INSERT INTO BOARD_TYPE
	(TYPE_CD, TYPE_NAME, TYPE_ENG_NAME, USE_YN)
SELECT
	'D', '자료실', 'board', 'Y'
FROM DUAL
WHERE NOT EXISTS (
	SELECT 1 FROM BOARD_TYPE WHERE TYPE_CD = 'D'
);

INSERT INTO BOARD_TYPE
	(TYPE_CD, TYPE_NAME, TYPE_ENG_NAME, USE_YN)
SELECT
	'E', '제품문의', 'inquiry', 'Y'
FROM DUAL
WHERE NOT EXISTS (
	SELECT 1 FROM BOARD_TYPE WHERE TYPE_CD = 'E'
);
